// Personal
export const APPLY_PERSONAL_FOR_SENDING_DATA_ACTION = 'APPLY_PERSONAL_FOR_SENDING_DATA_ACTION';
export const LOAD_SHIFT_DATA_FOR_DSP_ACTION = 'LOAD_SHIFT_DATA_FOR_DSP_ACTION';
export const LOAD_SHIFT_DATA_FOR_DNC_ACTION = 'LOAD_SHIFT_DATA_FOR_DNC_ACTION';
export const LOAD_SHIFT_DATA_FOR_ECD_ACTION = 'LOAD_SHIFT_DATA_FOR_ECD_ACTION';
export const LOAD_CURR_SECTORS_SHIFT_ACTION = 'LOAD_CURR_SECTORS_SHIFT_ACTION';

// Orders
export const CONFIRM_ORDER_ACTION = 'CONFIRM_ORDER_ACTION';
export const CONFIRM_ORDER_FOR_OTHERS_ACTION = 'CONFIRM_ORDER_FOR_OTHERS_ACTION';
export const CONFIRM_ORDER_FOR_OTHER_RECEIVERS_ACTION = 'CONFIRM_ORDER_FOR_OTHER_RECEIVERS_ACTION';
export const DEL_CONFIRMED_ORDERS_FROM_CHAIN_ACTION = 'DEL_CONFIRMED_ORDERS_FROM_CHAIN_ACTION';
export const DISPATCH_ORDER_ACTION = 'DISPATCH_ORDER_ACTION';
export const EDIT_DISPATCHED_ORDER_ACTION = 'EDIT_DISPATCHED_ORDER_ACTION';
export const DEL_STATION_WORK_PLACE_RECEIVER_ACTION = 'DEL_STATION_WORK_PLACE_RECEIVER_ACTION';
export const LOAD_WORK_ORDERS_ACTION = 'LOAD_WORK_ORDERS_ACTION';
export const LOAD_INCOMING_ORDERS_PER_SHIFT_ACTION = 'LOAD_INCOMING_ORDERS_PER_SHIFT_ACTION';
export const REPORT_ON_ORDERS_DELIVERY_ACTION = 'REPORT_ON_ORDERS_DELIVERY_ACTION';
export const LOAD_LAST_ORDERS_PARAMS_ACTION = 'LOAD_LAST_ORDERS_PARAMS_ACTION';
export const CHECK_CLIPBOARD = 'CHECK_CLIPBOARD';

// User
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const TRY_LOGIN_VIA_SESSION_ACTION = 'TRY_LOGIN_VIA_SESSION_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

// Current Work Poligon
export const LOAD_STATION_DATA_ACTION = 'LOAD_STATION_DATA_ACTION';
export const LOAD_DNC_SECTOR_DATA_ACTION = 'LOAD_DNC_SECTOR_DATA_ACTION';
export const LOAD_ECD_SECTOR_DATA_ACTION = 'LOAD_ECD_SECTOR_DATA_ACTION';
export const LOAD_CURR_WORK_POLIGON_DATA_ACTION = 'LOAD_CURR_WORK_POLIGON_DATA_ACTION';

// Order Drafts
export const LOAD_ORDER_DRAFTS_ACTION = 'LOAD_ORDER_DRAFTS_ACTION';
export const SAVE_ORDER_DRAFT_ACTION = 'SAVE_ORDER_DRAFT_ACTION';
export const EDIT_ORDER_DRAFT_ACTION = 'EDIT_ORDER_DRAFT_ACTION';
export const DEL_ORDER_DRAFT_ACTION = 'DEL_ORDER_DRAFT_ACTION';

// Order Patterns
export const LOAD_ORDER_PATTERNS_ACTION = 'LOAD_ORDER_PATTERNS_ACTION';
export const EDIT_ORDER_CATEGORY_TITLE_ACTION = 'EDIT_ORDER_CATEGORY_TITLE_ACTION';
export const DEL_ORDER_PATTERN_ACTION = 'DEL_ORDER_PATTERN_ACTION';
export const MOD_ORDER_PATTERN_ACTION = 'MOD_ORDER_PATTERN_ACTION';
export const CREATE_ORDER_PATTERN_ACTION = 'CREATE_ORDER_PATTERN_ACTION';
export const LOAD_ORDER_PATTERNS_ELEMENTS_REFS_ACTION = 'LOAD_ORDER_PATTERNS_ELEMENTS_REFS_ACTION';

// Local Storage
export const STORE_ORDERS_LOCALLY = 'STORE_ORDERS_LOCALLY';
