// Confirm Order
export const SET_CONFIRM_ORDER_RESULT = 'SET_CONFIRM_ORDER_RESULT';
export const SET_CONFIRM_ORDER_FOR_OTHERS_RESULT = 'SET_CONFIRM_ORDER_FOR_OTHERS_RESULT';
export const CLEAR_CONFIRM_ORDER_RESULT = 'CLEAR_CONFIRM_ORDER_RESULT';
export const CLEAR_CONFIRM_ORDER_FOR_OTHERS_RESULT = 'CLEAR_CONFIRM_ORDER_FOR_OTHERS_RESULT';
export const SET_ORDER_BEING_CONFIRMED = 'SET_ORDER_BEING_CONFIRMED';
export const SET_ORDER_BEING_CONFIRMED_FOR_OTHERS = 'SET_ORDER_BEING_CONFIRMED_FOR_OTHERS';
export const SET_ORDER_FINISHED_BEING_CONFIRMED = 'SET_ORDER_FINISHED_BEING_CONFIRMED';
export const SET_ORDER_FINISHED_BEING_CONFIRMED_FOR_OTHERS = 'SET_ORDER_FINISHED_BEING_CONFIRMED_FOR_OTHERS';
export const SET_CONFIRM_ORDER_RESULT_SEEN_BY_USER = 'SET_CONFIRM_ORDER_RESULT_SEEN_BY_USER';
export const SET_CONFIRM_ORDER_FOR_OTHERS_RESULT_SEEN_BY_USER = 'SET_CONFIRM_ORDER_FOR_OTHERS_RESULT_SEEN_BY_USER';
export const CLEAR_ALL_CONFIRM_ORDERS_RESULTS_SEEN_BY_USER = 'CLEAR_ALL_CONFIRM_ORDERS_RESULTS_SEEN_BY_USER';
export const CLEAR_ALL_CONFIRM_ORDERS_FOR_OTHERS_RESULTS_SEEN_BY_USER = 'CLEAR_ALL_CONFIRM_ORDERS_FOR_OTHERS_RESULTS_SEEN_BY_USER';
export const SET_ORDER_CONFIRMED = 'SET_ORDER_CONFIRMED';
export const SET_ORDER_CONFIRMED_FOR_OTHERS = 'SET_ORDER_CONFIRMED_FOR_OTHERS';
export const SET_ORDER_CONFIRMED_FOR_OTHER_RECEIVERS = 'SET_ORDER_CONFIRMED_FOR_OTHER_RECEIVERS';
export const SET_ORDER_ASSERT_DATE_TIME = 'SET_ORDER_ASSERT_DATE_TIME';
export const SET_CHANGE_ORDER_INVALID_MARK_RESULT = 'SET_CHANGE_ORDER_INVALID_MARK_RESULT';
export const SET_ORDER_BEING_CHANGED_ITS_INVALID_MARK = 'SET_ORDER_BEING_CHANGED_ITS_INVALID_MARK';
export const SET_ORDER_FINISHED_BEING_CHANGED_ITS_INVALID_MARK = 'SET_ORDER_FINISHED_BEING_CHANGED_ITS_INVALID_MARK';
export const CLEAR_CHANGE_ORDER_INVALID_MARK_RESULT = 'CLEAR_CHANGE_ORDER_INVALID_MARK_RESULT';
export const SET_ORDER_INVALID_MARK = 'SET_ORDER_INVALID_MARK';
export const SET_CHANGE_ORDER_INVALID_MARK_RESULTS_SEEN_BY_USER = 'SET_CHANGE_ORDER_INVALID_MARK_RESULTS_SEEN_BY_USER';
export const CLEAR_ALL_CHANGE_ORDER_INVALID_MARK_RESULTS_SEEN_BY_USER = 'CLEAR_ALL_CHANGE_ORDER_INVALID_MARK_RESULTS_SEEN_BY_USER';

// Main Menu Items
export const DETERMINE_LOGOUT_ITEM_ACTION = 'DETERMINE_LOGOUT_ITEM_ACTION';
export const SET_ACTIVE_MAIN_MENU_ITEM = 'SET_ACTIVE_MAIN_MENU_ITEM';

// Orders
export const SET_CAN_EDIT_EXISTING_TAKE_DUTY_ORDER = 'SET_CAN_EDIT_EXISTING_TAKE_DUTY_ORDER';
export const SET_SHOW_CREATE_DSP_TAKE_DUTY_ORDER_DLG = 'SET_SHOW_CREATE_DSP_TAKE_DUTY_ORDER_DLG';
export const CLEAR_DISPATCH_ORDER_RESULT = 'CLEAR_DISPATCH_ORDER_RESULT';
export const CLEAR_EDIT_DISPATCHED_ORDER_RESULT = 'CLEAR_EDIT_DISPATCHED_ORDER_RESULT';
export const ADD_ORDERS_BEING_DISPATCHED_NUMBER = 'ADD_ORDERS_BEING_DISPATCHED_NUMBER';
export const SUB_ORDERS_BEING_DISPATCHED_NUMBER = 'SUB_ORDERS_BEING_DISPATCHED_NUMBER';
export const SET_DISPATCH_ORDER_RESULT = 'SET_DISPATCH_ORDER_RESULT';
export const SET_EDIT_DISPATCHED_ORDER_RESULT = 'SET_EDIT_DISPATCHED_ORDER_RESULT';
export const SET_DEL_STATION_WORK_PLACE_RECEIVER_RESULT = 'SET_DEL_STATION_WORK_PLACE_RECEIVER_RESULT';
export const CLEAR_DEL_STATION_WORK_PLACE_RECEIVER_RESULT = 'CLEAR_DEL_STATION_WORK_PLACE_RECEIVER_RESULT';
export const CLEAR_ALL_DEL_STATION_WORK_PLACE_RECEIVER_RESULTS_SEEN_BY_USER = 'CLEAR_ALL_DEL_STATION_WORK_PLACE_RECEIVER_RESULTS_SEEN_BY_USER';
export const SET_DEL_STATION_WORK_PLACE_RECEIVER_RESULTS_SEEN_BY_USER = 'SET_DEL_STATION_WORK_PLACE_RECEIVER_RESULTS_SEEN_BY_USER';
export const SET_ORDER_BEING_DELETED_STATION_WORK_PLACE_RECEIVER = 'SET_ORDER_BEING_DELETED_STATION_WORK_PLACE_RECEIVER';
export const SET_ORDER_FINISHED_BEING_DELETED_STATION_WORK_PLACE_RECEIVER = 'SET_ORDER_FINISHED_BEING_DELETED_STATION_WORK_PLACE_RECEIVER';
export const DEL_ORDER_STATION_RECEIVER = 'DEL_ORDER_STATION_RECEIVER';
export const ADD_ORDER = 'ADD_ORDER';
export const EDIT_ORDER_TEXT = 'EDIT_ORDER_TEXT';
export const SET_DATA_FOR_DR_ORDER_GOT_FROM_CLIPBOARD = 'SET_DATA_FOR_DR_ORDER_GOT_FROM_CLIPBOARD';
export const CLEAR_DATA_FOR_DR_ORDER_GOT_FROM_CLIPBOARD = 'CLEAR_DATA_FOR_DR_ORDER_GOT_FROM_CLIPBOARD';

// Last Orders Params
export const DEL_CURR_LAST_ORDERS_PARAMS = 'DEL_CURR_LAST_ORDERS_PARAMS';
export const SET_LAST_ORDERS_NUMBER = 'SET_LAST_ORDERS_NUMBER';
export const RESET_ORDER_NUMBERS_DATA = 'RESET_ORDER_NUMBERS_DATA';
export const SET_LAST_ORDERS_PARAMS = 'SET_LAST_ORDERS_PARAMS';
export const CLEAR_LOADING_LAST_ORDERS_RESULT = 'CLEAR_LOADING_LAST_ORDERS_RESULT';
export const SET_LOADING_LAST_ORDERS_RESULT = 'SET_LOADING_LAST_ORDERS_RESULT';
export const SET_LOADING_LAST_ORDERS_PARAMS_STATUS = 'SET_LOADING_LAST_ORDERS_PARAMS_STATUS';

// Order Pattern Elements Refs
export const SET_LOADING_ORDER_PATTERNS_ELEMENTS_REFS_STATUS = 'SET_LOADING_ORDER_PATTERNS_ELEMENTS_REFS_STATUS';
export const SET_LOADING_REFS_RESULT = 'SET_LOADING_REFS_RESULT';
export const CLEAR_LOADING_REFS_RESULT = 'CLEAR_LOADING_REFS_RESULT';
export const SET_ORDER_PATTERNS_ELEMENTS_REFS = 'SET_ORDER_PATTERNS_ELEMENTS_REFS';
export const DEL_ORDER_PATTERNS_ELEMENTS_REFS = 'DEL_ORDER_PATTERNS_ELEMENTS_REFS';

// Incoming Orders Per Shift
export const SET_INCOMING_ORDERS_PER_SHIFT = 'SET_INCOMING_ORDERS_PER_SHIFT';
export const RESET_INCOMING_ORDERS_PER_SHIFT = 'RESET_INCOMING_ORDERS_PER_SHIFT';
export const CLEAR_GETTING_INCOMING_ORDERS_PER_SHIFT_RESULT = 'CLEAR_GETTING_INCOMING_ORDERS_PER_SHIFT_RESULT';
export const SET_GETTING_INCOMING_ORDERS_PER_SHIFT_RESULT = 'SET_GETTING_INCOMING_ORDERS_PER_SHIFT_RESULT';
export const SET_GETTING_INCOMING_ORDERS_PER_SHIFT_STATUS = 'SET_GETTING_INCOMING_ORDERS_PER_SHIFT_STATUS';

// Del Work Orders Chains
export const SET_DELETE_ORDERS_CHAIN_RESULT = 'SET_DELETE_ORDERS_CHAIN_RESULT';
export const SET_DELETE_ORDERS_CHAIN_RESULT_SEEN_BY_USER = 'SET_DELETE_ORDERS_CHAIN_RESULT_SEEN_BY_USER';
export const CLEAR_DELETE_ORDERS_CHAIN_RESULT = 'CLEAR_DELETE_ORDERS_CHAIN_RESULT';
export const CLEAR_ALL_DELETE_ORDERS_CHAIN_RESULTS_SEEN_BY_USER = 'CLEAR_ALL_DELETE_ORDERS_CHAIN_RESULTS_SEEN_BY_USER';
export const SET_ORDERS_CHAIN_BEING_DELETED = 'SET_ORDERS_CHAIN_BEING_DELETED';
export const SET_ORDERS_CHAIN_FINISHED_BEING_DELETED = 'SET_ORDERS_CHAIN_FINISHED_BEING_DELETED';
export const DELETE_CONFIRMED_ORDERS_CHAIN = 'DELETE_CONFIRMED_ORDERS_CHAIN';

// Get Work Orders
export const SET_START_DATE_TO_GET_DATA = 'SET_START_DATE_TO_GET_DATA';
export const SET_START_DATE_TO_GET_DATA_NO_CHECK = 'SET_START_DATE_TO_GET_DATA_NO_CHECK';
export const CLEAR_LOADING_WORK_ORDERS_RESULT = 'CLEAR_LOADING_WORK_ORDERS_RESULT';
export const SET_LOADING_WORK_ORDERS_RESULT = 'SET_LOADING_WORK_ORDERS_RESULT';
export const SET_LOADING_WORK_ORDERS_STATUS = 'SET_LOADING_WORK_ORDERS_STATUS';
export const SET_NEW_WORK_ORDERS_ARRAY = 'SET_NEW_WORK_ORDERS_ARRAY';
export const UPDATE_NUMBER_OF_INCOMING_ORDERS_PER_SHIFT = 'UPDATE_NUMBER_OF_INCOMING_ORDERS_PER_SHIFT';
export const DEL_WORK_ORDERS = 'DEL_WORK_ORDERS';

// Incoming Orders
export const NOTIFIED_ABOUT_NEW_INCOMING_ORDERS = 'NOTIFIED_ABOUT_NEW_INCOMING_ORDERS';

// Report On Orders Delivery
export const SET_ORDERS_DELIVERED = 'SET_ORDERS_DELIVERED';
export const CLEAR_REPORT_ON_ORDERS_DELIVERY_RESULT = 'CLEAR_REPORT_ON_ORDERS_DELIVERY_RESULT';
export const SET_REPORT_ON_ORDERS_DELIVERY_RESULT = 'SET_REPORT_ON_ORDERS_DELIVERY_RESULT';
export const SET_REPORTING_ON_ORDER_DELIVERY_STATUS = 'SET_REPORTING_ON_ORDER_DELIVERY_STATUS';

// Curr Date Time
export const SET_CURR_DATE_TIME = 'SET_CURR_DATE_TIME';

// Curr User
export const SET_USER_CREDENTIAL = 'SET_USER_CREDENTIAL';
export const SET_USER_WORK_POLIGON = 'SET_USER_WORK_POLIGON';
export const SET_USER_TOKEN = 'SET_USER_TOKEN';
export const SET_USER_PASS_DUTY_TIME = 'SET_USER_PASS_DUTY_TIME';
export const SET_USER_TAKE_PASS_DUTY_TIMES = 'SET_USER_TAKE_PASS_DUTY_TIMES';
export const CANCEL_LOGOUT = 'CANCEL_LOGOUT';
export const PREPARE_FOR_LOGOUT = 'PREPARE_FOR_LOGOUT';
export const START_LOGOUT_PROCESS = 'START_LOGOUT_PROCESS';
export const LOGOUT_FINISHED_WITH_ERROR = 'LOGOUT_FINISHED_WITH_ERROR';
export const LOGOUT_FINISHED_WITHOUT_ERROR = 'LOGOUT_FINISHED_WITHOUT_ERROR';
export const SET_USER_DATA_ON_LOGIN = 'SET_USER_DATA_ON_LOGIN';
export const CLEAR_USER_DATA_ON_LOGOUT = 'CLEAR_USER_DATA_ON_LOGOUT';
export const CLEAR_LOGIN_RESULT = 'CLEAR_LOGIN_RESULT';
export const SET_LOGIN_RESULT = 'SET_LOGIN_RESULT';
export const SET_USER_OFFLINE_STATUS = 'SET_USER_OFFLINE_STATUS';
export const SET_USER_ALL_WORK_OFFLINE_STATUS = 'SET_USER_ALL_WORK_OFFLINE_STATUS';

// Curr Work Poligon Structure
export const SET_ERROR_LOADING_CURR_WORK_POLIGON_DATA = 'SET_ERROR_LOADING_CURR_WORK_POLIGON_DATA';
export const SET_LOADING_CURR_WORK_POLIGON_DATA_STATUS = 'SET_LOADING_CURR_WORK_POLIGON_DATA_STATUS';
export const DEL_CURR_WORK_POLIGON_DATA = 'DEL_CURR_WORK_POLIGON_DATA';


// Order Patterns
export const DEL_CURR_ORDER_PATTERN_DATA = 'DEL_CURR_ORDER_PATTERN_DATA';
export const SET_NEW_ORDER_PATTERNS_ARRAY = 'SET_NEW_ORDER_PATTERNS_ARRAY';
export const SET_LOADING_ORDER_PATTERNS_STATUS = 'SET_LOADING_ORDER_PATTERNS_STATUS';
export const CLEAR_LOADING_ORDER_PATTERNS_RESULT = 'CLEAR_LOADING_ORDER_PATTERNS_RESULT';
export const SET_LOADING_ORDER_PATTERNS_RESULT = 'SET_LOADING_ORDER_PATTERNS_RESULT';
export const CLEAR_MODIFY_ORDER_CATEGORY_TITLE_RESULT = 'CLEAR_MODIFY_ORDER_CATEGORY_TITLE_RESULT';
export const SET_MODIFY_ORDER_CATEGORY_TITLE_RESULT = 'SET_MODIFY_ORDER_CATEGORY_TITLE_RESULT';
export const ADD_MODIFY_ORDER_CATEGORY_TITLE_RECS_BEING_PROCESSED = 'ADD_MODIFY_ORDER_CATEGORY_TITLE_RECS_BEING_PROCESSED';
export const SUB_MODIFY_ORDER_CATEGORY_TITLE_RECS_BEING_PROCESSED = 'SUB_MODIFY_ORDER_CATEGORY_TITLE_RECS_BEING_PROCESSED';
export const SET_ORDER_CATEGORY_TITLE = 'SET_ORDER_CATEGORY_TITLE';
export const CLEAR_DEL_ORDER_PATTERN_RESULT = 'CLEAR_DEL_ORDER_PATTERN_RESULT';
export const SET_DEL_ORDER_PATTERN_RESULT = 'SET_DEL_ORDER_PATTERN_RESULT';
export const ADD_DEL_ORDER_PATTERN_RECS_BEING_PROCESSED = 'ADD_DEL_ORDER_PATTERN_RECS_BEING_PROCESSED';
export const SUB_DEL_ORDER_PATTERN_RECS_BEING_PROCESSED = 'SUB_DEL_ORDER_PATTERN_RECS_BEING_PROCESSED';
export const DEL_ORDER_PATTERN = 'DEL_ORDER_PATTERN';
export const CLEAR_MOD_ORDER_PATTERN_RESULT = 'CLEAR_MOD_ORDER_PATTERN_RESULT';
export const SET_MOD_ORDER_PATTERN_RESULT = 'SET_MOD_ORDER_PATTERN_RESULT';
export const ADD_MOD_ORDER_PATTERN_RECS_BEING_PROCESSED = 'ADD_MOD_ORDER_PATTERN_RECS_BEING_PROCESSED';
export const SUB_MOD_ORDER_PATTERN_RECS_BEING_PROCESSED = 'SUB_MOD_ORDER_PATTERN_RECS_BEING_PROCESSED';
export const MOD_ORDER_PATTERN = 'MOD_ORDER_PATTERN';
export const CLEAR_CREATE_ORDER_PATTERN_RESULT = 'CLEAR_CREATE_ORDER_PATTERN_RESULT';
export const SET_CREATE_ORDER_PATTERN_RESULT = 'SET_CREATE_ORDER_PATTERN_RESULT';
export const ADD_CREATE_ORDER_PATTERN_RECS_BEING_PROCESSED = 'ADD_CREATE_ORDER_PATTERN_RECS_BEING_PROCESSED';
export const SUB_CREATE_ORDER_PATTERN_RECS_BEING_PROCESSED = 'SUB_CREATE_ORDER_PATTERN_RECS_BEING_PROCESSED';
export const ADD_NEW_ORDER_PATERN = 'ADD_NEW_ORDER_PATERN';

// Personal
export const CLEAR_SHIFT_FOR_SENDING_DATA = 'CLEAR_SHIFT_FOR_SENDING_DATA';
export const SET_GET_ORDER_STATUS_TO_ALL_DNC_SECTORS = 'SET_GET_ORDER_STATUS_TO_ALL_DNC_SECTORS';
export const SET_GET_ORDER_STATUS_TO_DEFINIT_DNC_SECTOR = 'SET_GET_ORDER_STATUS_TO_DEFINIT_DNC_SECTOR';
export const SET_GET_ORDER_STATUSES_TO_ONLY_DEFINIT_SECTORS = 'SET_GET_ORDER_STATUSES_TO_ONLY_DEFINIT_SECTORS';
export const SET_GET_ORDER_STATUS_TO_ALL_LEFT_DNC_SECTORS = 'SET_GET_ORDER_STATUS_TO_ALL_LEFT_DNC_SECTORS';
export const SET_DEFAULT_DSP_ADDRESSES = 'SET_DEFAULT_DSP_ADDRESSES';
export const SET_GET_ORDER_STATUS_TO_ALL_DSP = 'SET_GET_ORDER_STATUS_TO_ALL_DSP';
export const SET_GET_ORDER_STATUS_TO_DEFINIT_DSP = 'SET_GET_ORDER_STATUS_TO_DEFINIT_DSP';
export const SET_GET_ORDER_STATUS_TO_ALL_LEFT_DSP = 'SET_GET_ORDER_STATUS_TO_ALL_LEFT_DSP';
export const SET_GET_ORDER_STATUS_TO_ALL_ECD_SECTORS = 'SET_GET_ORDER_STATUS_TO_ALL_ECD_SECTORS';
export const SET_GET_ORDER_STATUS_TO_DEFINIT_ECD_SECTOR = 'SET_GET_ORDER_STATUS_TO_DEFINIT_ECD_SECTOR';
export const SET_GET_ORDER_STATUS_TO_ALL_LEFT_ECD_SECTORS = 'SET_GET_ORDER_STATUS_TO_ALL_LEFT_ECD_SECTORS';
export const SET_GET_ORDER_STATUS_TO_ALL_OTHER_SHIFT = 'SET_GET_ORDER_STATUS_TO_ALL_OTHER_SHIFT';
export const SET_GET_ORDER_STATUS_TO_DEFINIT_OTHER_SHIFT = 'SET_GET_ORDER_STATUS_TO_DEFINIT_OTHER_SHIFT';
export const SET_GET_ORDER_STATUS_TO_ALL_LEFT_OTHER_SHIFT = 'SET_GET_ORDER_STATUS_TO_ALL_LEFT_OTHER_SHIFT';
export const SET_ONLINE_SHIFT_PERSONAL = 'SET_ONLINE_SHIFT_PERSONAL';
export const CHOOSE_ONLY_ONLINE_PERSONAL = 'CHOOSE_ONLY_ONLINE_PERSONAL';
export const SET_USER_CHOSEN_STATUS = 'SET_USER_CHOSEN_STATUS';
export const ADD_OTHER_GET_ORDER_RECORD = 'ADD_OTHER_GET_ORDER_RECORD';
export const REWRITE_OTHER_GET_ORDER_RECORD = 'REWRITE_OTHER_GET_ORDER_RECORD';
export const EDIT_OTHER_GET_ORDER_RECORD = 'EDIT_OTHER_GET_ORDER_RECORD';
export const DEL_OTHER_GET_ORDER_RECORD = 'DEL_OTHER_GET_ORDER_RECORD';
export const DEL_OTHER_GET_ORDER_RECORD_BY_ADDITIONAL_ID = 'DEL_OTHER_GET_ORDER_RECORD_BY_ADDITIONAL_ID';
export const DEL_CURR_SECTORS_SHIFT = 'DEL_CURR_SECTORS_SHIFT';
export const SET_OTHER_SHIFT_FOR_SENDING_DATA = 'SET_OTHER_SHIFT_FOR_SENDING_DATA';
export const SET_ERROR_LOADING_CURR_SHIFT = 'SET_ERROR_LOADING_CURR_SHIFT';
export const SET_LOADING_CURR_SECTOR_SHIFT_STATUS = 'SET_LOADING_CURR_SECTOR_SHIFT_STATUS';
export const SET_SECTOR_PERSONAL = 'SET_SECTOR_PERSONAL';
export const CLEAR_OTHER_SHIFT = 'CLEAR_OTHER_SHIFT';

// WebSocket
export const SET_SERVER_MESSAGE = 'SET_SERVER_MESSAGE';
export const SET_WS_READY_STATE = 'SET_WS_READY_STATE';
export const RESET_RETRY_NUM = 'RESET_RETRY_NUM';
export const NEXT_RETRY_NUM = 'NEXT_RETRY_NUM';
export const RETRY_ON_CLOSE_WS_CONNECTION = 'RETRY_ON_CLOSE_WS_CONNECTION';
export const DO_NOT_RETRY_ON_CLOSE_WS_CONNECTION = 'DO_NOT_RETRY_ON_CLOSE_WS_CONNECTION';
export const DEL_ALL_WS_SERVER_MESSAGES = 'DEL_ALL_WS_SERVER_MESSAGES';

// Common
export const SHOW_APP_SETTINGS = 'SHOW_APP_SETTINGS';
export const SHOW_ORDER_DRAFTS = 'SHOW_ORDER_DRAFTS';
export const SET_PRINT_PREVIEW = 'SET_PRINT_PREVIEW';
export const SET_SYSTEM_MESSAGE = 'SET_SYSTEM_MESSAGE';
export const DELETE_ALL_SYSTEM_MESSAGES = 'DELETE_ALL_SYSTEM_MESSAGES';
export const SET_ALL_DATA_LOADED_ON_APP_RELOAD = 'SET_ALL_DATA_LOADED_ON_APP_RELOAD';

// Order Drafts
export const SET_LOADING_ORDER_DRAFTS_RESULT = 'SET_LOADING_ORDER_DRAFTS_RESULT';
export const CLEAR_LOADING_ORDER_DRAFTS_RESULT = 'CLEAR_LOADING_ORDER_DRAFTS_RESULT';
export const SET_LOADING_ORDER_DRAFTS_STATUS = 'SET_LOADING_ORDER_DRAFTS_STATUS';
export const SET_ORDER_DRAFTS_ARRAY = 'SET_ORDER_DRAFTS_ARRAY';
export const SET_SAVE_ORDER_DRAFT_RESULT = 'SET_SAVE_ORDER_DRAFT_RESULT';
export const SET_DEL_ORDER_DRAFT_RESULT = 'SET_DEL_ORDER_DRAFT_RESULT';
export const CLEAR_SAVE_ORDER_DRAFT_RESULT = 'CLEAR_SAVE_ORDER_DRAFT_RESULT';
export const CLEAR_DEL_ORDER_DRAFT_RESULT = 'CLEAR_DEL_ORDER_DRAFT_RESULT';
export const ADD_ORDER_DRAFT = 'ADD_ORDER_DRAFT';
export const DEL_ORDERS_DRAFTS = 'DEL_ORDERS_DRAFTS';
export const EDIT_ORDER_DRAFT = 'EDIT_ORDER_DRAFT';
export const DEL_ORDER_DRAFT = 'DEL_ORDER_DRAFT';
export const SET_DELETED_ORDER_DRAFT_ID = 'SET_DELETED_ORDER_DRAFT_ID';
export const DRAFT_FINISHED_BEING_DELETED = 'DRAFT_FINISHED_BEING_DELETED';

// Okna
export const SET_SELECTED_OKNO = 'SET_SELECTED_OKNO';
