export const MIN_SOUND_VALUE = 0;
export const MAX_SOUND_VALUE = 1;
export const CHANGE_SOUND_STEP = 0.1;
export const MAX_SYSTEM_MESSAGES_STORED = 50;

export const UPDATE_CURR_DATE_TIME_INTERVAL = +process.env.VUE_APP_UPDATE_CURR_DATE_TIME_INTERVAL || 1000;
export const REQUEST_NEW_ORDERS_FROM_SERVER_INTERVAL = +process.env.VUE_APP_REQUEST_NEW_ORDERS_FROM_SERVER_INTERVAL || 30000;
